export const KeyboardMapping: {[name: string]: {[name: string]: number}} = {
    //  Code: KeyCode
    
    'ShiftLeft':    {'keyCode': 16},
    'ControlLeft':  {'keyCode': 17},
    'AltLeft':      {'keyCode': 18},
    
    'Space':        {'keyCode': 32},

    'ArrowLeft':    {'keyCode': 37},
    'ArrowUp':      {'keyCode': 38},
    'ArrowRight':   {'keyCode': 39},
    'ArrowDown':    {'keyCode': 40},

    'Digit0':   {'keyCode': 48},
    'Digit1':   {'keyCode': 49},
    'Digit2':   {'keyCode': 50},
    'Digit3':   {'keyCode': 51},
    'Digit4':   {'keyCode': 52},
    'Digit5':   {'keyCode': 53},
    'Digit6':   {'keyCode': 54},
    'Digit7':   {'keyCode': 55},
    'Digit8':   {'keyCode': 56},
    'Digit9':   {'keyCode': 57},

    'KeyA': {'keyCode': 65},
    'KeyB': {'keyCode': 66},
    'KeyC': {'keyCode': 67},
    'KeyD': {'keyCode': 68},
    'KeyE': {'keyCode': 69},
    'KeyF': {'keyCode': 70},
    'KeyG': {'keyCode': 71},
    'KeyH': {'keyCode': 72},
    'KeyI': {'keyCode': 73},
    'KeyJ': {'keyCode': 74},
    'KeyK': {'keyCode': 75},
    'KeyL': {'keyCode': 76},
    'KeyM': {'keyCode': 77},
    'KeyN': {'keyCode': 78},
    'KeyO': {'keyCode': 79},
    'KeyP': {'keyCode': 80},
    'KeyQ': {'keyCode': 81},
    'KeyR': {'keyCode': 82},
    'KeyS': {'keyCode': 83},
    'KeyT': {'keyCode': 84},
    'KeyU': {'keyCode': 85},
    'KeyV': {'keyCode': 86},
    'KeyW': {'keyCode': 87},
    'KeyX': {'keyCode': 88},
    'KeyY': {'keyCode': 89},
    'KeyZ': {'keyCode': 90},

    'Numpad0':  {'keyCode': 96},
    'Numpad1':  {'keyCode': 97},
    'Numpad2':  {'keyCode': 98},
    'Numpad3':  {'keyCode': 99},
    'Numpad4':  {'keyCode': 100},
    'Numpad5':  {'keyCode': 101},
    'Numpad6':  {'keyCode': 102},
    'Numpad7':  {'keyCode': 103},
    'Numpad8':  {'keyCode': 104},
    'Numpad9':  {'keyCode': 105}
}